import { chromium } from 'playwright';
const EXE = '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const url = process.argv[2];
const out = process.argv[3];
const w = Number(process.argv[4] || 1100), h = Number(process.argv[5] || 1400);
const b = await chromium.launch({ executablePath: EXE, args: ['--no-sandbox'] });
const p = await b.newPage({ viewport: { width: w, height: h } });
await p.goto(url, { waitUntil: 'networkidle' });
await p.waitForTimeout(800);
const c = await p.$('#view') || await p.$('canvas');
await (c ? c.screenshot({ path: out }) : p.screenshot({ path: out }));
await b.close();
